### ISSUE TITLE
dde-workspace fails to build with go-1.5-1

### ISSUE THREAD

**Issue by mmetak** [fasheng/arch-deepin#83]
I've updated go to 1.5 in OBS and dde-workspace fails to build with this error:

[  269s] Scanning dependencies of target desktop
[  269s] [ 51%] Building C object app/desktop/CMakeFiles/desktop.dir/desktop.c.o
[  270s] /usr/src/packages/BUILD/dde-workspace/src/deepin-desktop-environment-2.1+20150521160615/app/desktop/desktop.c:45:26: fatal error: DBUS_desktop.h: No such file or directory
[  270s] compilation terminated.

**Comment by fasheng** [comment]
Solved with a patch about go template. Closed.
